version: '3.3'
services:
  db:
    image: mysql:9
    restart: always
    environment:
      MYSQL_DATABASE: 'api'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db-data:/var/lib/mysql
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db-data: